### PR TITLE
adding datasets to EVCFLO/datasets

### PR DESCRIPTION
**Pull request by jamiecdavidson**

### CODE REVIEW

**Review by west557 — COMMENTED** [review]
It seems okay. Thanks

**Review by west557 — APPROVED** [review]
Approved.

**Review by west557 — APPROVED** [review]
Approved.

**Review by west557 — APPROVED** [review]
All good. Changed the data sets. Looks okay. Approved.

**Review by west557 — APPROVED** [review]
Approved. Added datasets.

**Review by west557 — APPROVED** [review]

**Review by west557 — APPROVED** [review]

**Review by m1ckw — APPROVED** [review]
Looks good. Approved.

**Pull request merged**
